AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  transactions-importer

  Sample SAM Template for transactions-importer

Globals:
  Function:
    Timeout: 3

Resources:
  TransactionsImporterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        ImportEvent:
          Type: Api
          Properties:
            Path: /import
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  TransactionsImporterAPI:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TransactionsImporterFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt TransactionsImporterFunction.Arn
  TransactionsImporterFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt TransactionsImporterFunctionRole.Arn
